source 'https://rubygems.org'

gem 'fluentd', '1.15.3'
gem 'fluent-plugin-test', '1.1.0'
gem 'fluentd-ui', '1.0.7'
gem 'fluent-plugin-concat', '2.5.1'
gem 'fluent-plugin-elasticsearch', '5.3.2'
gem 'fluent-plugin-kubernetes_metadata_filter', '2.8.0'
gem 'fluent-plugin-multi-format-parser', '1.1.0'
gem 'fluent-plugin-prometheus', '1.9.0'
gem 'fluent-plugin-systemd', '1.0.0'
gem 'fluent-plugin-ec2-metadata', '0.4.1'
gem 'fluent-plugin-s3', '1.6.2'
gem 'fluent-plugin-kinesis', '1.3.1'
gem 'fluent-plugin-kafka', '1.1.5'
gem 'fluent-plugin-opensearch', '1.1.0'
gem 'fluent-plugin-rewrite-tag-filter', '2.4.0'
gem 'fluent-plugin-parser-cri', '2.2.0'
gem 'fluent-plugin-dedot_filter', '2.0.0'
gem 'fluent-plugin-cloudwatch-logs', '0.7.0'
gem 'fluent-plugin-splunk-enterprise', '1.2.0'
gem 'fluent-plugin-sampling-filter', '1.0.0'
gem 'fluent-diagtool', '0.1.0'
gem 'fluent-plugin-fluent-cat', '0.5.1'