source 'https://rubygems.org'

gem 'fluentd', '1.15.3'
gem 'fluent-plugin-test'
gem 'fluentd-ui', '1.2.1'
gem 'fluent-plugin-concat', '2.5.0'
gem 'fluent-plugin-elasticsearch', '5.2.4'
gem 'fluent-plugin-kubernetes_metadata_filter', '3.1.2'
gem 'fluent-plugin-multi-format-parser', '1.0.0'
gem 'fluent-plugin-prometheus', '2.0.3'
gem 'fluent-plugin-systemd', '1.0.5'
gem 'fluent-plugin-ec2-metadata', '0.1.3'
gem 'fluent-plugin-s3', '1.7.2'
gem 'fluent-plugin-kinesis', '3.4.2'
gem 'fluent-plugin-kafka', '0.18.1'
gem 'fluent-plugin-opensearch', '~> 1.0', '>= 1.0.9'
gem 'fluent-plugin-rewrite-tag-filter', '~> 2.4'
gem 'fluent-plugin-parser-cri', '~> 0.1.1'
gem 'fluent-plugin-dedot_filter', '1.0.0'
gem 'fluent-plugin-cloudwatch-logs', '~> 0.14.3'
gem 'fluent-plugin-splunk-enterprise', '~> 0.10.2'
gem 'fluent-plugin-sampling-filter', '~> 1.2'
gem 'fluent-diagtool', '~> 1.0', '>= 1.0.1'
gem 'fluent-plugin-cat-sweep'